[profile.default]
src = "src"
out = "out"
libs = ["lib", "node_modules"]
remappings = [
    "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/",
    "forge-std/=lib/forge-std/src/"
]

solc = "0.8.24"
evm_version = "cancun"
